name: Check





on: push





jobs:

  checking:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run test -- --verbose
      - run: npm run build

      - uses: codecov/codecov-action@v1
        timeout-minutes: 1

